### ISSUE TITLE
Wget & space in pathnames (macOS)

### ISSUE THREAD

**Issue by Biegz** [sbu-ces-unofficial/copy-catcher#4]
-Need to install wget for macOS
-Account for spaces in pathnames for macOS

**Comment by pchan37** [comment]
Note the space issue is not restricted to macOS only.  The build script would need significant modification before it would work on macOS native.

**Comment by pchan37** [comment]
This should no longer be an issue after 354e4ca8cbf24bacec67215bbec73bc4a1ba9bf0.
